### ISSUE TITLE
Changes required for AppCenter: include data directory in build system

### ISSUE THREAD

**Issue by cassidyjames** [dcharles525/pho#16]
It looks like when adding translations, your data directory was inadvertently removed from your meson build system. This means your data files (like icons) are no longer being included in the package.

https://github.com/dcharles525/pho/commit/53121c1c5a1611a88f121a143b70a2e30bc153d5#diff-969b60ad3d206fd45c208e266ccfed38L35

**Comment by dcharles525** [comment]
Ahhh I was trying to figure out what was wrong. Thanks for pointing it out!
