### ISSUE TITLE
Changes Requested: Accurate OARS data

### ISSUE THREAD

**Issue by cassidyjames** [dcharles525/pho#4]
Hey @dcharles525 in reviewing your app, we realized your OARS data is inaccurate. Since users can easily navigate (with a click or two) to many forms of explicit content, we require that your OARS data reflect this. I ran through the [OARS generator](https://hughsie.github.io/oars/generate.html) based on my experience with the app and came up with the following data:

```
<content_rating type="oars-1.1">
  <content_attribute id="violence-sexual">intense</content_attribute>
  <content_attribute id="sex-nudity">intense</content_attribute>
  <content_attribute id="sex-themes">intense</content_attribute>
  <content_attribute id="sex-prostitution">intense</content_attribute>
  <content_attribute id="sex-adultery">intense</content_attribute>
  <content_attribute id="sex-appearance">intense</content_attribute>
  <content_attribute id="language-profanity">intense</content_attribute>
  <content_attribute id="language-humor">intense</content_attribute>
  <content_attribute id="language-discrimination">intense</content_attribute>
  <content_attribute id="social-chat">intense</content_attribute>
</content_rating>
```

This is probably not complete, but would cover most things. Protip: choose the dropdown that says your app is a game, even though it's not. The generator currently omits a lot of relevant fields if you don't mark it as a game.

**Comment by dcharles525** [comment]
Whoops totally forgot to do this, I went through the OARS generator and updated the appdata file. Thank you!
